# Generated by Django 5.1.4 on 2025-01-03 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('specialty', models.CharField(max_length=30, verbose_name='Specialty')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_time', models.DateTimeField(verbose_name='Time of reception')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='patient_manage.doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='patient_manage.patient')),
            ],
        ),
    ]
