# Generated by Django 5.1.4 on 2025-01-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_manage', '0002_alter_appointment_doctor_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('patient', models.ManyToManyField(related_name='diagnoses', to='patient_manage.patient')),
            ],
        ),
    ]
